### ISSUE TITLE
Add Windows CI config

### ISSUE THREAD

**Issue by gbtami** [beeware/gbulb#25]
After noticing that PyGI AIO supports silent install from 3.18.2 rev11 I'v managed to use it in PyChess to run tests on Windows using appveyor.com
https://github.com/pychess/pychess/blob/master/appveyor.yml

Of course you can add more Python versions to the matrix and gbulb tests needs to install GTK module only.

**Comment by freakboy3742** [comment]
We're adopting Github Actions as a CI framework; if anyone wants to add a CI config for Windows, I'd be open to merging that PR.

**Comment by freakboy3742** [comment]
Actually - I'm going to close this in favour of #51; no point having Windows CI support unless there's support for Windows.
