### ISSUE TITLE
Windows: gbulb does not work with asyncio lib aioopenssl

### ISSUE THREAD

**Issue by lovetox** [beeware/gbulb#33]
Hi,

I tested gbulb with an openssl lib thats based on asyncio. It connects to a server verifys the cert and so on

The lib has some tests and they work until i place `gbulb.install(gtk=True)` into the test

- For reproduction install aioopenssl
- open file `test_e2e.py`
- place `gbulb.install(gtk=True)` somewhere at the top after imports
- execute `python3 -m unittest tests/test_e2e.py`

i hope someone could look into that, maybe some problem with sockets and how they work on Windows

**Comment by lovetox** [comment]
One random thing i found which could maybe be a clue (or not)

https://docs.python.org/3.5/library/asyncio-eventloops.html#windows

says `EventLoopPolicy.set_child_watcher()  is not supported`

from a quick look at the code it seems gbulb uses this

**Comment by freakboy3742** [comment]
The project README indicates that Windows is not currently supported. Closing on that basis.
