### ISSUE TITLE
request for release

### ISSUE THREAD

**Issue by grindhold** [beeware/gbulb#67]
### Describe the bug

i have a problem where i cant use asyncssh's portforwarding anymore with python 3.11 and gbulb.  i urgently need line 436 in `glib_events.py`  .  Python 3.11 calls the method with 8 parameters instead of 7 (counting `self`  as a parameter). in 0.6.3, this line is missing.

do you guys plan on making a release anytime soon? i'd rather not monkeypatch that :)

### Steps to reproduce

0. use python 3.11 instead of python 3.10
1. make a gtk app that works together with asyncssh
2. try to tunnel a remote unix socket to the application host
3. enjoy a nice has-nothing-to-do-with-anything-message and an unexpected connection close
4. print-debug your way through the stack
5. finish at line 436 in glib_events.py
6. add additional parameter which defaults to None
7. behold that stuff works again

### Expected behavior

stuff should work without having to patch gbulbs code

### Environment

- Operating System: Debian bookworm
- Python version: 3.11
- Software versions:
 gbulb: 0.6.3

### Logs

```

```

**Comment by freakboy3742** [comment]
Thanks for the prod - a release was definitely overdue. I've just published v0.6.4 that includes the Py 3.11 (and initial Py 3.12) changes.

**Comment by grindhold** [comment]
wow! that was quick! thank you very much :)
